name: PR Test
on:
  pull_request:
    branches:
      - develop
      - release
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test