name: Publish en GitHub Packages

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - develop
      - 'feature/**'
      - 'release/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Tests on ${{ github.ref_name }}
        run: ./gradlew test

  publish:
    name: Publish Package (Only on PR to Master) on ${{ github.ref_name }} in  ${{ github.event_name }} si ${{ github.base_ref }}
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'pull_request' && github.base_ref == 'master'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.PUBLIC_TOKEN_REPOSITORY }}
