name: CI/CD – lib-microservices-configuration

on:
  pull_request:
    branches:
      - master
      - develop
      - release
      - 'release/**'
      #- test
      #- uat

  #push:
  #  branches:
  #    - 'feature/**'
  #    - 'release/**'

jobs:
  build-and-test:
    #name: Test on ${{ github.ref_name }} event ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Tests on ${{ github.ref_name }}
        run: ./gradlew test

  publish:
    #name: Publish Package (PR to master from ${{ github.head_ref }})
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'release'
    #if: startsWith(github.href,'refs/heads/release/' )
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.PUBLIC_TOKEN_REPOSITORY }}
