name: Build & Push Docker Image

on:
  pull_request:
    branches:
      - release
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Give permission to gradlew
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew clean build

      - name: Generate semantic version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          tag_prefix: "v"
          bump_each_commit: false
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat"
          patch_pattern: "fix"

      - name: Show version
        run: echo "Calculated version is ${{ steps.version.outputs.version }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}